swagger: '2.0'

# TestServer Error Object definitions
info:
  version: "2.2.0"
  title: TestServer Global Model

definitions:
  DfScmUrl:
    type: string
    description: The DF SCM URL of this revision of the source file as defined by CodeServer

  ErrorResponse:
    type: object
    properties:
      errors:
        type: array
        items:
          $ref: "#/definitions/Error"

  Error:
    type: object
    properties:
      code:
        type: integer
      message:
        description: A brief message describing the general nature of the error, for example Invalid Attribute
        type: string
      detail:
        description: Detail specific to this occurrence of the error, e.g. Test Suite ID not valid.
        type: string

